[project]
name = "vis-loc"
version = "1.0.0"
description = "Localizing using relative location of objects and a webcam"
authors = [{name = "K Herbstzuber", email = "kmherbstzuber@wpi.edu"}]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipython>=9.17.1",
    "matplotlib>=3.11.2",
    "nbconvert>=7.17.1",
    "pandas>=3.0.6",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]

[build-system]
requires = ["uv_build >= 0.12.19, <0.13.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
minversion = "9.0"
addopts = "-p pytest_cov -ra -q --cov=vis_loc --cov-report=term-missing"
testpaths = [
    "tests"
]

[tool.coverage.run]
omit = ["**/__init__.py"]
branch = true
source = ["vis_loc"]

[dependency-groups]
dev = [
    "uv-script>=0.1.9",
]

[tool.uv.build-backend]
module-name = "vis_loc"
module-root = ""
source-exclude = [ # exclude from both source and wheel
  "**/.*",           
  "/.github",   
  "/docs",
  "/logs",
  "/plots",
  "uv.lock",
  "*.log"
]
wheel-exclude = [
  "benchmarks/**",
   "/tests"
]

[project.scripts]
test = "tests.run_tests:main"
sim = "vis_loc.run:main"
