import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from mpl_toolkits.axes_grid1 import make_axes_locatable

# to-do list
    # setting colors
        # color schemes
        # individual elements (robot, rays, etc.)
    # move the field plotting here as well...
    
class Render:
    def __init__(self, ax):
        # field base plot
        self.ax = ax

        # for the particle filter graphics
        self.pf_cbar = None
        self.pf_pose_arrow = None  
        self.pf_quiver = None

        # for the robot graphics
        self.bot_marker = None
        self.bot_arrow = None 


    @staticmethod
    def remove_element(attribute):
        '''
        helper function to remove something from a matplotlib plot

        Args:
            attribute: element on the matplotlib plot
        '''
        
        if attribute is not None:
            try:
                attribute.remove()
            except Exception as e:
               pass
            attribute = None


    def render(self):
        '''redraw / rerender the matplotlib plot'''
        
        try:
            self.ax.figure.canvas.draw_idle()
        except Exception:
            pass


    def particles(self, particles, weights):
        '''
        renders particles (small pose arrows) on a matplotlib plot.
        function was formerly in the Localize class (localize.py)

        Args:
            particles: the particles generated by the Localize class
            weights: the weights associated with each particle
        '''

        Render.remove_element(self.pf_quiver)
        Render.remove_element(self.pf_cbar)

        if particles is None or len(particles) == 0:
            return

        x = particles[:, 0]
        y = particles[:, 1]
        th = particles[:, 2]

        rad = np.radians(th)
        dx = np.cos(rad) * 0.4
        dy = np.sin(rad) * 0.4
        
        self.pf_quiver = self.ax.quiver(y, x, dy, dx, weights, scale=1, scale_units='xy', 
                                    angles='xy', alpha=0.8, cmap='plasma')
        
        divider = make_axes_locatable(self.ax)
        cax = divider.append_axes("right", size="3%", pad=0.1)
        self.pf_cbar = self.ax.figure.colorbar(self.pf_quiver, cax=cax)
        self.pf_cbar.set_label('particle weight')

        self.render()


    def estimated_pose(self, pose:tuple):
        '''
        draws the estimated pose from the filter on a matplotlib plot.
        function was formerly in the Localize class (localize.py)

        Args:
            pose: the estimated pose from the particle filter
        '''

        x, y, th = pose

        # remove previous single pose arrow (if present)
        self.remove_element(self.pf_pose_arrow)

        # draw pose estimate arrow on plot 
        rad = np.radians(th)
        dx = np.cos(rad) * 0.4
        dy = np.sin(rad) * 0.4

        self.pf_pose_arrow = self.ax.arrow(y, x, dy, dx, head_width=0.2, head_length=0.3, fc='red', ec='red')

        self.render()


    def camera_view(self, camera_data):
        fig, ax = plt.subplots(figsize=(14, 3))

        # if nothing is visible, show nothing and return
        if not camera_data:
            ax.set_title('Camera Output (no visible goals)')
            ax.set_xlabel('Relative Degree (0 = straight ahead)')
            ax.axvline(x=0, color='black', linestyle='--', alpha=0.5)
            plt.show()
            plt.close(fig)
            return

        colors = []
        xs = []

        for color, rel in camera_data:
            xs.append(rel)
            if color == 0:
                colors.append('black')
            elif color == 1:
                colors.append('blue')
            elif color == 2:
                colors.append('red')
            else:
                colors.append('gray')

        ax.bar(xs, np.ones(len(xs)), color=colors, width=0.8)
        ax.set_xlabel('Relative Degree (0 = straight ahead)')
        ax.set_title('Camera Output (occlusion-aware)')
        ax.axvline(x=0, color='black', linestyle='--', alpha=0.5)
        plt.show()
        plt.close(fig)

    
